#!/bin/bash
#
# A simple framework for testing the tn scripts
#
# Returns the number of failed test cases.
#
# Format of a test:
#     test 'command' expected_return_value 'stdin text' 'expected stdout' 'expected stderr'
#
# Some example test cases are given. You should add more test cases.
#
# Sam Scott, McMaster University, 2024


# GLOBALS: tc = test case number, fails = number of failed cases
declare -i tc=0
declare -i fails=0

############################################
# Run a single test. Runs a given command 3 times
# to check the return value, stdout, and stderr
#
# GLOBALS: tc, fails
# PARAMS: $1 = command
#         $2 = expected return value
#         $3 = standard input text to send
#         $4 = expected stdout
#         $5 = expected stderr
# RETURNS: 0 = success, 1 = bad return, 
#          2 = bad stdout, 3 = bad stderr
############################################
test() {
    tc=tc+1

    local COMMAND=$1
    local RETURN=$2
	local STDIN=$3
    local STDOUT=$4
    local STDERR=$5

    # CHECK RETURN VALUE
    $COMMAND <<< "$STDIN" >/dev/null 2>/dev/null
    local A_RETURN=$?

    if [[ "$A_RETURN" != "$RETURN" ]]; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected Return: $RETURN"
        echo "   Actual Return: $A_RETURN"
        fails=$fails+1
        return 1
    fi

    # CHECK STDOUT
    local A_STDOUT=$($COMMAND <<< "$STDIN" 2>/dev/null)

    if [[ "$STDOUT" != "$A_STDOUT" ]]; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected STDOUT: $STDOUT"
        echo "   Actual STDOUT: $A_STDOUT"
        fails=$fails+1
        return 2
    fi
    
    # CHECK STDERR
    local A_STDERR=$($COMMAND <<< "$STDIN" 2>&1 >/dev/null)

    if [[ "$STDERR" != "$A_STDERR" ]]; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected STDERR: $STDERR"
        echo "   Actual STDERR: $A_STDERR"
        fails=$fails+1
        return 3
    fi
    
    # SUCCESS
    echo "Test $tc Passed"
    return 0
}

##########################################
# EXAMPLE TEST CASES
##########################################

# simple success
test './tn' 0 'Ashlyn Krueger' "Women's Tennis 2025
===================
Ashlyn Krueger
    21 wins, 22 losses" ''

# multi line input
test './tn M' 0 'Jakub Mensik
Mikhail Kukushkin
Sam Scott' "Men's Tennis 2025
===================
Jakub Mensik
    34 wins, 21 losses
Mikhail Kukushkin
    0 wins, 2 losses
Sam Scott
    0 wins, 0 losses" ''

# error case
test 'tn -t 1999 m w' 1 '' '' "Too many parameters
Usage: tn [<-t>] [<year>] [<men's or women's: m|M|w|W>]"

# error case with standard output as well
test './tn 1977 w' 3 'Elizabeth Vlotman
Elizabeth
Elizabeth7' "Women's Tennis 1977
===================
Elizabeth Vlotman
    3 wins, 1 losses
Elizabeth
    0 wins, 0 losses" 'Badly formatted name: Elizabeth7'  

# return code
exit $fails
